import { motion } from "framer-motion";

export default function ReportSummary({ summary, metrics, patientInfo, results }) {
  const handlePrint = () => window.print();

  return (
    <motion.div
      className="glass card-3d rounded-2xl p-8 mt-6"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
    >
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <span className="text-2xl">📋</span>
          <h2 className="text-xl font-bold text-white">Analysis Report</h2>
        </div>
        <div className="flex gap-3">
          <button onClick={handlePrint} className="btn-secondary text-sm">
            🖨️ Print
          </button>
          <button onClick={handlePrint} className="btn-primary text-sm !py-2 !px-4">
            📥 Download
          </button>
        </div>
      </div>

      <div className="section-divider" />

      {/* Patient Info */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <div>
          <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">Patient</p>
          <p className="text-sm font-medium">{patientInfo.name || "—"}</p>
        </div>
        <div>
          <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">ID</p>
          <p className="text-sm font-medium font-mono">{patientInfo.id || "—"}</p>
        </div>
        <div>
          <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">Age</p>
          <p className="text-sm font-medium">{patientInfo.age || "—"}</p>
        </div>
        <div>
          <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">Date</p>
          <p className="text-sm font-medium">{patientInfo.date || new Date().toLocaleDateString()}</p>
        </div>
      </div>

      <div className="section-divider" />

      {/* Diagnosis */}
      <div className="flex items-center gap-4 mb-4">
        <div>
          <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">Final AI Diagnosis</p>
          <p className={`text-2xl font-bold ${
            summary.patientPrediction === "CANCER POSITIVE" ? "text-[#FF006E]" : "text-[#00FF88]"
          }`}>
            {summary.patientPrediction}
          </p>
        </div>
        <span className={`badge ${
          summary.patientPrediction === "CANCER POSITIVE" ? "badge-danger" : "badge-success"
        }`}>
          {summary.patientPrediction === "CANCER POSITIVE" ? "HIGH RISK" : "LOW RISK"}
        </span>
      </div>
      <p className="text-xs text-gray-400 mb-6 max-w-2xl">
        <b>Clinical Context:</b> This diagnosis is generated using the <i>QuantumFusion</i> architecture (Xception backbone with Quantum Entanglement Feature Fusion). It analyzes morphological features of all uploaded cells to estimate the overall blast cell ratio.
      </p>

      {/* Summary stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <div className="glass rounded-xl p-4 text-center">
          <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">Cells Analyzed</p>
          <p className="text-xl font-bold text-white">{summary.total}</p>
        </div>
        <div className="glass rounded-xl p-4 text-center">
          <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">Blast Cells</p>
          <p className="text-xl font-bold text-[#FF006E]">{summary.cancerCount}</p>
        </div>
        <div className="glass rounded-xl p-4 text-center">
          <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">Normal Cells</p>
          <p className="text-xl font-bold text-[#00FF88]">{summary.normalCount}</p>
        </div>
        <div className="glass rounded-xl p-4 text-center group relative">
          <p className="text-[10px] text-gray-500 uppercase tracking-wider mb-1">Blast Ratio</p>
          <p className="text-xl font-bold text-[#3A86FF]">
            {summary.total > 0 ? ((summary.cancerCount / summary.total) * 100).toFixed(1) : 0}%
          </p>
          {/* Tooltip */}
          <div className="absolute inset-x-0 bottom-full mb-2 hidden group-hover:block z-10 bg-[rgba(10,15,36,0.95)] backdrop-blur-md p-2 rounded-lg text-xs text-gray-300">
            Ratio of leukemic blasts to total cells. &gt;20% often indicates acute leukemia in bone marrow.
          </div>
        </div>
      </div>

      {/* Model Metrics */}
      <div className="grid grid-cols-4 gap-3">
        {Object.entries(metrics).map(([k, v]) => (
          <div key={k} className="text-center">
            <p className="text-[10px] text-gray-500 uppercase tracking-wider">{k}</p>
            <p className="text-sm font-bold text-[#3A86FF]">{(v * 100).toFixed(1)}%</p>
          </div>
        ))}
      </div>

      <div className="section-divider" />

      <p className="text-[10px] text-gray-600 text-center">
        This report is generated by BloodScan AI v1.0 — For clinical reference only.
        Always consult a qualified hematologist for final diagnosis.
      </p>
    </motion.div>
  );
}
